---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: prepare_files
  pull: default
  image: alpine:3.7
  commands:
  - source versions.txt
  - export BACKEND_VERSION
  - export FRONTEND_VERSION
  - echo $${BACKEND_VERSION}
  - echo $${FRONTEND_VERSION}
  - mkdir /tmp/infomark
  - cd /tmp/infomark
  - wget https://github.com/infomark-org/infomark/releases/download/$${BACKEND_VERSION}/infomark.tar.gz
  - tar -xzvf infomark.tar.gz
  - rm infomark.tar.gz
  - cp /tmp/infomark/api.yaml /drone/src/docs/static/swagger/api.yaml
  - cp /tmp/infomark/infomark /drone/src/infomark

- name: build_docs
  pull: never
  image: patwie/hugo:v1
  commands:
  - mkdir /tmp/console_docs
  - ./infomark console utils doc /tmp/console_docs
  - cp -r /tmp/console_docs/* /drone/src/docs/content/guides/console
  - rm /drone/src/infomark
  - cd /drone/src/docs
  - hugo version
  - hugo

- name: publish_pages
  pull: never
  image: patwie/deploy_docs:v1
  commands:
  - /opt/publish.sh

trigger:
  branch:
  - master

---
kind: signature
hmac: bb4bec36a477409590e313879afc0bc272d02646384092a7d6881de925ebb4f9

...
