baseURL = "https://infomark.org"
languageCode = "en-us"
title = "InfoMark"
theme = "infomark.org"

pygmentsCodeFences = true
pygmentsStyle = "friendly"
pygmentsCodefencesGuessSyntax = true
pygmentsuseclasses = true

